package com.community.healthcare;

import com.jayway.jsonpath.JsonPath;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder;
import org.springframework.web.context.WebApplicationContext;
import tools.jackson.databind.ObjectMapper;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.LocalDateTime;
import java.util.HexFormat;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.jwt;
import static org.springframework.security.test.web.servlet.setup.SecurityMockMvcConfigurers.springSecurity;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
import static org.springframework.test.web.servlet.setup.MockMvcBuilders.webAppContextSetup;

@SpringBootTest(properties =
        "spring.datasource.url=jdbc:h2:mem:r2-api;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1")
@ActiveProfiles("demo")
class R2SchedulingEncounterIntegrationTests {
    @Autowired WebApplicationContext context;
    @Autowired ObjectMapper mapper;
    @Autowired JdbcTemplate jdbc;
    MockMvc mvc;

    @BeforeEach
    void setUp() {
        mvc = webAppContextSetup(context).apply(springSecurity()).build();
        jdbc.execute("create table if not exists staff_profile (id bigint generated by default as identity primary key, organization_id bigint not null, staff_no varchar(64) not null unique, name varchar(128) not null, staff_type varchar(32) not null, account_status varchar(32) not null, active boolean not null, created_at timestamp not null, updated_at timestamp not null, version bigint not null)");
    }

    @Test
    void appointmentToSignedEncounterIsOwnedIdempotentAndAudited() throws Exception {
        Fixture f = fixture();
        LocalDateTime start = LocalDateTime.now().plusDays(2).withSecond(0).withNano(0);
        MvcResult session = staffJson(post("/api/v1/staff/scheduling/sessions"), f.doctorStaffId, "DOCTOR", Map.of(
                        "siteId", f.siteId, "departmentId", f.departmentId,
                        "startsAt", start.toString(), "endsAt", start.plusMinutes(60).toString(),
                        "slotMinutes", 30))
                .andExpect(status().isCreated()).andExpect(jsonPath("$.slotIds.length()").value(2)).andReturn();
        long slotId = ((Number) JsonPath.read(body(session), "$.slotIds[0]")).longValue();

        MockHttpServletRequestBuilder book = post("/api/v1/resident/scheduling/appointments")
                .header("Idempotency-Key", "book-" + f.suffix);
        MvcResult first = residentJson(book, f.patientId, Map.of("slotId", slotId, "reason", "血压复诊"))
                .andExpect(status().isCreated()).andExpect(jsonPath("$.status").value("CONFIRMED")).andReturn();
        long appointmentId = number(first, "$.id");
        MvcResult replay = residentJson(post("/api/v1/resident/scheduling/appointments")
                        .header("Idempotency-Key", "book-" + f.suffix), f.patientId,
                        Map.of("slotId", slotId, "reason", "血压复诊"))
                .andExpect(status().isOk()).andReturn();
        assertThat(number(replay, "$.id")).isEqualTo(appointmentId);

        residentJson(delete("/api/v1/resident/scheduling/appointments/{id}", appointmentId),
                f.otherPatientId, Map.of()).andExpect(status().isNotFound());

        staffJson(post("/api/v1/staff/scheduling/appointments/{id}/check-in", appointmentId),
                f.nurseStaffId, "NURSE", Map.of())
                .andExpect(status().isOk()).andExpect(jsonPath("$.status").value("CHECKED_IN"));
        MvcResult encounter = staffJson(post("/api/v1/staff/scheduling/appointments/{id}/start", appointmentId),
                f.doctorStaffId, "DOCTOR", Map.of())
                .andExpect(status().isCreated()).andExpect(jsonPath("$.status").value("DRAFT")).andReturn();
        long encounterId = number(encounter, "$.id");

        staffJson(put("/api/v1/staff/encounters/{id}/draft", encounterId), f.doctorStaffId, "DOCTOR",
                Map.of("body", "S: 头晕；O: BP 146/92；A: 高血压；P: 调整生活方式", "version", 0))
                .andExpect(status().isOk()).andExpect(jsonPath("$.version").value(1));
        staffJson(put("/api/v1/staff/encounters/{id}/draft", encounterId), f.doctorStaffId, "DOCTOR",
                Map.of("body", "过期编辑", "version", 0)).andExpect(status().isConflict());
        staffJson(post("/api/v1/staff/encounters/{id}/diagnoses", encounterId), f.doctorStaffId, "DOCTOR",
                Map.of("code", "I10", "name", "原发性高血压", "type", "PRIMARY"))
                .andExpect(status().isCreated());
        staffJson(post("/api/v1/staff/encounters/{id}/sign", encounterId), f.doctorStaffId, "DOCTOR",
                Map.of("version", 1))
                .andExpect(status().isOk()).andExpect(jsonPath("$.status").value("SIGNED"));
        staffJson(post("/api/v1/staff/encounters/{id}/diagnoses", encounterId), f.doctorStaffId, "DOCTOR",
                Map.of("code", "E11", "name", "2 型糖尿病", "type", "SECONDARY"))
                .andExpect(status().isConflict());

        String immutableDocument = jdbc.queryForObject(
                "select content from clinical_document_version where encounter_id = ?", String.class, encounterId);
        assertThat(immutableDocument).contains("I10", "原发性高血压", "PRIMARY");
        String immutableHash = jdbc.queryForObject(
                "select content_hash from clinical_document_version where encounter_id = ?", String.class, encounterId);
        assertThat(immutableHash).isEqualTo(HexFormat.of().formatHex(
                MessageDigest.getInstance("SHA-256").digest(immutableDocument.getBytes(StandardCharsets.UTF_8))));

        jdbc.update("update clinical_encounter set status='AMENDED' where id=?", encounterId);
        staffJson(post("/api/v1/staff/encounters/{id}/diagnoses", encounterId), f.doctorStaffId, "DOCTOR",
                Map.of("code", "J44", "name", "慢性阻塞性肺疾病", "type", "SECONDARY"))
                .andExpect(status().isConflict());
        jdbc.update("update clinical_encounter set status='VOID' where id=?", encounterId);
        staffJson(post("/api/v1/staff/encounters/{id}/diagnoses", encounterId), f.doctorStaffId, "DOCTOR",
                Map.of("code", "J44", "name", "慢性阻塞性肺疾病", "type", "SECONDARY"))
                .andExpect(status().isConflict());
        assertThat(jdbc.queryForObject("select count(*) from clinical_diagnosis where encounter_id = ?",
                Integer.class, encounterId)).isEqualTo(1);

        assertThat(jdbc.queryForObject("select status from sched_appointment where id = ?", String.class, appointmentId))
                .isEqualTo("COMPLETED");
        assertThat(jdbc.queryForObject("select count(*) from clinical_document_version where encounter_id = ?",
                Integer.class, encounterId)).isEqualTo(1);
        assertThat(jdbc.queryForObject("select count(*) from audit_event where action = 'ENCOUNTER_SIGNED' and resource_id = ?",
                Integer.class, String.valueOf(encounterId))).isEqualTo(1);
    }

    @Test
    void oneSlotCanOnlyBeReservedOnce() throws Exception {
        Fixture f = fixture();
        LocalDateTime start = LocalDateTime.now().plusDays(3).withSecond(0).withNano(0);
        long slotId = ((Number) JsonPath.read(body(staffJson(post("/api/v1/staff/scheduling/sessions"),
                        f.doctorStaffId, "DOCTOR", Map.of("siteId", f.siteId, "departmentId", f.departmentId,
                                "startsAt", start.toString(), "endsAt", start.plusMinutes(30).toString(), "slotMinutes", 30))
                .andExpect(status().isCreated()).andReturn()), "$.slotIds[0]")).longValue();

        residentJson(post("/api/v1/resident/scheduling/appointments").header("Idempotency-Key", "p1-" + f.suffix),
                f.patientId, Map.of("slotId", slotId, "reason", "首位居民"))
                .andExpect(status().isCreated());
        residentJson(post("/api/v1/resident/scheduling/appointments").header("Idempotency-Key", "p2-" + f.suffix),
                f.otherPatientId, Map.of("slotId", slotId, "reason", "第二位居民"))
                .andExpect(status().isConflict());
        assertThat(jdbc.queryForObject("select count(*) from sched_appointment where slot_id = ?", Integer.class, slotId))
                .isEqualTo(1);
    }

    @Test
    void doctorSchedulingAndNurseCheckInAreRestrictedToActiveAssignments() throws Exception {
        Fixture f = fixture();
        LocalDateTime start = LocalDateTime.now().plusDays(4).withSecond(0).withNano(0);

        long unassignedDepartment = department(f.siteId, "R2X-" + f.suffix);
        staffJson(post("/api/v1/staff/scheduling/sessions"), f.doctorStaffId, "DOCTOR", Map.of(
                        "siteId", f.siteId, "departmentId", unassignedDepartment,
                        "startsAt", start.toString(), "endsAt", start.plusMinutes(30).toString(),
                        "slotMinutes", 30))
                .andExpect(status().isForbidden());

        MvcResult session = staffJson(post("/api/v1/staff/scheduling/sessions"),
                f.doctorStaffId, "DOCTOR", Map.of(
                        "siteId", f.siteId, "departmentId", f.departmentId,
                        "startsAt", start.toString(), "endsAt", start.plusMinutes(30).toString(),
                        "slotMinutes", 30))
                .andExpect(status().isCreated()).andReturn();
        long slotId = ((Number) JsonPath.read(body(session), "$.slotIds[0]")).longValue();
        long appointmentId = number(residentJson(post("/api/v1/resident/scheduling/appointments")
                        .header("Idempotency-Key", "scope-" + f.suffix), f.patientId,
                        Map.of("slotId", slotId, "reason", "站点范围测试"))
                .andExpect(status().isCreated()).andReturn(), "$.id");

        long otherSite = site("R2Y-" + f.suffix);
        long otherNurse = staff(organizationOfSite(otherSite), f.suffix + "X", "NURSE");
        assign(otherNurse, otherSite, null, "NURSE", LocalDateTime.now().minusDays(1), null, true);
        staffJson(post("/api/v1/staff/scheduling/appointments/{id}/check-in", appointmentId),
                otherNurse, "NURSE", Map.of()).andExpect(status().isForbidden());

        jdbc.update("update staff_site_assignment set valid_to=? where staff_profile_id=?",
                LocalDateTime.now().minusMinutes(1), f.nurseStaffId);
        staffJson(post("/api/v1/staff/scheduling/appointments/{id}/check-in", appointmentId),
                f.nurseStaffId, "NURSE", Map.of()).andExpect(status().isForbidden());
    }

    private Fixture fixture() {
        String suffix = UUID.randomUUID().toString().replace("-", "").substring(0, 10);
        jdbc.update("insert into organization(code,name,active,created_at,updated_at,version) values(?,?,true,current_timestamp,current_timestamp,0)",
                "R2O-" + suffix, "R2中心");
        long org = jdbc.queryForObject("select id from organization where code=?", Long.class, "R2O-" + suffix);
        jdbc.update("insert into site(organization_id,code,name,site_type,active,created_at,updated_at,version) values(?,?,?,'CENTER',true,current_timestamp,current_timestamp,0)",
                org, "R2S-" + suffix, "R2站点");
        long site = jdbc.queryForObject("select id from site where code=?", Long.class, "R2S-" + suffix);
        jdbc.update("insert into department(organization_id,site_id,code,name,active,created_at,updated_at,version) values(?,?,?,?,true,current_timestamp,current_timestamp,0)",
                org, site, "R2D-" + suffix, "全科");
        long dept = jdbc.queryForObject("select id from department where code=?", Long.class, "R2D-" + suffix);
        long doctor = staff(org, suffix + "D", "DOCTOR");
        long nurse = staff(org, suffix + "N", "NURSE");
        assign(doctor, site, dept, "DOCTOR", LocalDateTime.now().minusDays(1), null, true);
        assign(nurse, site, null, "NURSE", LocalDateTime.now().minusDays(1), null, true);
        long patient = patient("R2P" + suffix, "预约居民");
        long other = patient("R2Q" + suffix, "其他居民");
        return new Fixture(suffix, site, dept, doctor, nurse, patient, other);
    }

    private long staff(long org, String no, String type) {
        jdbc.update("insert into staff_profile(organization_id,staff_no,name,staff_type,account_status,active,created_at,updated_at,version) values(?,?,?,?,'ACTIVE',true,current_timestamp,current_timestamp,0)",
                org, no, type + no, type);
        return jdbc.queryForObject("select id from staff_profile where staff_no=?", Long.class, no);
    }

    private long site(String code) {
        String orgCode = code + "-ORG";
        jdbc.update("insert into organization(code,name,active,created_at,updated_at,version) values(?,?,true,current_timestamp,current_timestamp,0)",
                orgCode, "其他中心");
        long org = jdbc.queryForObject("select id from organization where code=?", Long.class, orgCode);
        jdbc.update("insert into site(organization_id,code,name,site_type,active,created_at,updated_at,version) values(?,?,?,'STATION',true,current_timestamp,current_timestamp,0)",
                org, code, "其他站点");
        return jdbc.queryForObject("select id from site where code=?", Long.class, code);
    }

    private long department(long site, String code) {
        long org = organizationOfSite(site);
        jdbc.update("insert into department(organization_id,site_id,code,name,active,created_at,updated_at,version) values(?,?,?,?,true,current_timestamp,current_timestamp,0)",
                org, site, code, "其他科室");
        return jdbc.queryForObject("select id from department where code=?", Long.class, code);
    }

    private long organizationOfSite(long site) {
        return jdbc.queryForObject("select organization_id from site where id=?", Long.class, site);
    }

    private void assign(long staff, long site, Long department, String role, LocalDateTime from,
                        LocalDateTime to, boolean active) {
        jdbc.update("insert into staff_site_assignment(staff_profile_id,site_id,department_id,role_code,valid_from,valid_to,active,created_at) values(?,?,?,?,?,?,?,current_timestamp)",
                staff, site, department, role, from, to, active);
    }

    private long patient(String idCard, String name) {
        jdbc.update("insert into patient(id_card,name,gender,birth_date,balance,active,created_at,updated_at,version) values(?,?,'其他','1990-01-01',0,true,current_timestamp,current_timestamp,0)", idCard, name);
        return jdbc.queryForObject("select id from patient where id_card=?", Long.class, idCard);
    }

    private org.springframework.test.web.servlet.ResultActions residentJson(
            MockHttpServletRequestBuilder request, long patientId, Object content) throws Exception {
        return mvc.perform(request.with(jwt().jwt(b -> b.subject("resident-" + patientId)
                        .claim("roles", List.of("RESIDENT")).claim("role", "RESIDENT")
                        .claim("patientId", patientId).claim("mustChangePassword", false))
                .authorities(new SimpleGrantedAuthority("ROLE_RESIDENT")))
                .contentType(MediaType.APPLICATION_JSON).content(mapper.writeValueAsString(content)));
    }

    private org.springframework.test.web.servlet.ResultActions staffJson(
            MockHttpServletRequestBuilder request, long staffId, String role, Object content) throws Exception {
        return mvc.perform(request.with(jwt().jwt(b -> b.subject(role.toLowerCase() + "-" + staffId)
                        .claim("roles", List.of(role)).claim("role", role).claim("staffId", staffId)
                        .claim("staffProfileId", staffId).claim("mustChangePassword", false))
                .authorities(new SimpleGrantedAuthority("ROLE_" + role)))
                .contentType(MediaType.APPLICATION_JSON).content(mapper.writeValueAsString(content)));
    }

    private long number(MvcResult result, String path) throws Exception {
        return ((Number) JsonPath.read(body(result), path)).longValue();
    }

    private String body(MvcResult result) throws Exception {
        return result.getResponse().getContentAsString(StandardCharsets.UTF_8);
    }

    private record Fixture(String suffix, long siteId, long departmentId, long doctorStaffId,
                           long nurseStaffId, long patientId, long otherPatientId) {}
}
