package com.community.healthcare.config;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.MigrationVersion;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.beans.factory.SmartInitializingSingleton;
import org.springframework.stereotype.Component;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * 为 Demo Profile 的内存 H2 数据库补齐 R8 基线依赖并执行后续 Flyway 迁移。
 *
 * <p>旧演示建表脚本缺少 R8 引入的人员与站点表，因此在 Flyway 以版本 8 建立基线前先创建最小结构。
 * 该兼容流程受配置开关限制，并主动拒绝非 H2 数据源，正式库必须走完整迁移链。</p>
 */
@Component
@ConditionalOnProperty(name = "app.demo-schema-migration.enabled", havingValue = "true")
public class DemoSchemaMigrationRunner implements SmartInitializingSingleton {
    private final DataSource dataSource;

    public DemoSchemaMigrationRunner(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    /** 在所有单例创建完成后执行，确保数据源已可用且早于业务请求进入。 */
    @Override
    public void afterSingletonsInstantiated() {
        try {
            requireH2();
            ensureJdbcPrerequisites();
            Flyway.configure()
                    .dataSource(dataSource)
                    .locations("classpath:db/migration")
                    .baselineOnMigrate(true)
                    .baselineVersion(MigrationVersion.fromVersion("8"))
                    .load()
                    .migrate();
        } catch (SQLException exception) {
            throw new IllegalStateException("Demo 数据库结构初始化失败", exception);
        }
    }

    private void requireH2() throws SQLException {
        try (Connection connection = dataSource.getConnection()) {
            if (!"H2".equalsIgnoreCase(connection.getMetaData().getDatabaseProductName())) {
                throw new IllegalStateException("Demo 模式仅支持 H2；正式数据库请使用 prod Profile");
            }
        }
    }

    /**
     * 创建迁移 V9–V11 所依赖的最小 R8 表结构。
     *
     * <p>语句保持幂等，允许 Demo 数据库已由其他初始化器提前创建这些表。</p>
     */
    private void ensureJdbcPrerequisites() throws SQLException {
        try (Connection connection = dataSource.getConnection(); Statement statement = connection.createStatement()) {
            statement.execute("create table if not exists staff_profile (id bigint generated by default as identity primary key, "
                    + "organization_id bigint not null, staff_no varchar(64) not null unique, name varchar(128) not null, "
                    + "staff_type varchar(32) not null, account_status varchar(32) not null, active boolean not null, "
                    + "created_at timestamp not null, updated_at timestamp not null, version bigint not null)");
            statement.execute("create table if not exists staff_site_assignment (id bigint generated by default as identity primary key, "
                    + "staff_profile_id bigint not null, site_id bigint not null, department_id bigint null, role_code varchar(32) not null, "
                    + "valid_from timestamp not null, valid_to timestamp null, active boolean not null, created_at timestamp not null)");
            statement.execute("create table if not exists patient_site_enrollment (id bigint generated by default as identity primary key, "
                    + "patient_id bigint not null, site_id bigint not null, enrolled_at timestamp not null, ended_at timestamp null, "
                    + "active boolean not null, created_at timestamp not null)");
        }
    }
}
